---
- name: Configure Switchports
  hosts: switches
  gather_facts: false
  connection: network_cli

  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: Get login credentials
      include_vars: group_vars/secrets2.yml

    - name: Interface configurations
      ios_config:
        authorize: yes
        parents: "interface {{ item.interface }}"
        lines: 
          - "switchport access vlan {{ item.vlan }}"
          - "switchport access vlan {{ item.voice_vlan}}"
        after:
          - no shutdown

      with_items:
        - { interface : GigabitEthernet2/1, vlan: 40, voice_vlan: 50 }
        - { interface : GigabitEthernet2/2, vlan: 40, voice_vlan: 50 }