---

- name: Get VLAN information
  hosts: switches
  gather_facts: false
  connection: network_cli

  vars:
    ansible_python_interpreter: /usr/bin/python3.8

  tasks:
    - name: Gather login creds
      include_vars: group_vars/secrets2.yml

    - name: Gather VLAN info
      ios_command:
        commands:
          - show version 
          - show vlan brief
          - show run | sec snmp
          - show run | sec access-list

      register: print_vlan_output

    - debug: var=print_vlan_output