---
- name: Configure Switchports
  hosts: switches
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3 
    cli: 
      username: carter
      password: cisco
  
  tasks:
    - name: Interface configurations
      ios_config:
        provider: "{{ cli }}"
        authorize: yes
        parents: "interface {{ item.interface }}"
        lines:
          - "switchport access vlan {{ item.vlan }}"
          - "switchport voice vlan {{ item.voice_vlan }}"
          - switchport host
          - switchport port-security maximum 2
          - switchport port-security
          - switchport port-security aging time 2
          - switchport port-security aging type inactivity
          - switchport port-security violation restrict
          - ip arp inspection limit rate 100
          - ip dhcp snooping limit rate 100
          - ip verify source
        after:
          - no shutdown
      with_items:
        - { interface : GigabitEthernet3/0, vlan : 40, voice_vlan : 50 }
        - { interface : GigabitEthernet3/1, vlan : 40, voice_vlan : 50 }
        - { interface : GigabitEthernet3/2, vlan : 30, voice_vlan : 50 }

      register: print_interface_output

    - debug: var=print_interface_output.std_out