---
- name: Add access-list
  hosts: switches
  gather_facts: false
  connection: local

  vars:
    ansible_python_interpreter: /usr/bin/python3 
    cli: 
      username: carter
      password: cisco
  
  tasks: 
    - name: Create VLANs
      ios_config: 
        authorize: yes
        provider: "{{ cli }}"
        lines:
          - vlan 10
          - vlan 20
          - vlan 30
          - vlan 40
          - vlan 50
          - vlan 60
          - vlan 70
          - vlan 80
          - vlan 90
          - vlan 100
      
      register: print_vlan_output

    - debug: var=print_vlan_output
